import { StencilCategory, StencilCollection } from '@/types/shapeLibrary';
import { DRAW_SCRIPTS } from '../scripts';

export const agileCollection: StencilCollection =   {
    id: 'prebuilt-agile-sprint',
    name: 'Agile & Sprint Teams',
    description: 'User stories, retrospective boards, planning poker chips, sprint goals, and blocker flags',
    categories: [StencilCategory.AGILE_SPRINT],
    isPrebuilt: true,
    stencils: [
      {
        id: 'agile-story-card',
        name: 'User Story Card',
        category: StencilCategory.AGILE_SPRINT,
        description: 'Parametric user story card with persona, goal, value, and estimation points badge',
        width: 240,
        height: 160,
        shapes: [
          {
            type: 'Custom',
            left: 0,
            top: 0,
            width: 240,
            height: 160,
            script: DRAW_SCRIPTS.agileStoryCard,
            properties: {
              code: 'US-101',
              title: 'User Authentication',
              persona: 'As a User',
              goal: 'I want to sign in with SSO',
              value: 'So that I access my boards quickly',
              points: '5',
              status: 'IN PROGRESS',
            },
            fillColor: '#fefce8',
            strokeColor: '#eab308',
            strokeWidth: 2,
            fontColor: '#713f12',
          },
        ],
      },
      {
        id: 'agile-planning-poker-set',
        name: 'Planning Poker Badges',
        category: StencilCategory.AGILE_SPRINT,
        description: 'Fibonacci estimation badges (1, 2, 3, 5, 8, 13)',
        width: 320,
        height: 50,
        shapes: [
          { type: 'Ellipse', left: 0, top: 0, width: 45, height: 45, fillColor: '#e0f2fe', strokeColor: '#0284c7', strokeWidth: 2, text: '1', fontColor: '#0369a1', fontSize: 16, fontWeight: 700, horzAlign: 'center', vertAlign: 'middle' },
          { type: 'Ellipse', left: 55, top: 0, width: 45, height: 45, fillColor: '#e0f2fe', strokeColor: '#0284c7', strokeWidth: 2, text: '2', fontColor: '#0369a1', fontSize: 16, fontWeight: 700, horzAlign: 'center', vertAlign: 'middle' },
          { type: 'Ellipse', left: 110, top: 0, width: 45, height: 45, fillColor: '#e0e7ff', strokeColor: '#4f46e5', strokeWidth: 2, text: '3', fontColor: '#3730a3', fontSize: 16, fontWeight: 700, horzAlign: 'center', vertAlign: 'middle' },
          { type: 'Ellipse', left: 165, top: 0, width: 45, height: 45, fillColor: '#fef3c7', strokeColor: '#d97706', strokeWidth: 2, text: '5', fontColor: '#92400e', fontSize: 16, fontWeight: 700, horzAlign: 'center', vertAlign: 'middle' },
          { type: 'Ellipse', left: 220, top: 0, width: 45, height: 45, fillColor: '#fee2e2', strokeColor: '#dc2626', strokeWidth: 2, text: '8', fontColor: '#991b1b', fontSize: 16, fontWeight: 700, horzAlign: 'center', vertAlign: 'middle' },
          { type: 'Ellipse', left: 275, top: 0, width: 45, height: 45, fillColor: '#f3e8ff', strokeColor: '#9333ea', strokeWidth: 2, text: '13', fontColor: '#6b21a8', fontSize: 16, fontWeight: 700, horzAlign: 'center', vertAlign: 'middle' },
        ],
      },
      {
        id: 'agile-retro-columns',
        name: 'Sprint Retrospective Columns',
        category: StencilCategory.AGILE_SPRINT,
        description: 'Standard 3-column retro board: What Went Well, To Improve, and Action Items',
        width: 870,
        height: 580,
        shapes: [
          {
            type: 'Frame',
            name: '🟢 What Went Well',
            title: '🟢 What Went Well',
            left: 0,
            top: 0,
            width: 270,
            height: 580,
            corners: [8, 8, 8, 8],
            fillColor: '#f0fdf4',
            strokeColor: '#22c55e',
            strokeWidth: 2,
          },
          {
            type: 'Rectangle',
            left: 20,
            top: 55,
            width: 230,
            height: 85,
            corners: [4, 4, 4, 4],
            fillColor: '#dcfce7',
            strokeColor: '#86efac',
            strokeWidth: 1,
            text: '🎉 Team collaboration\nwas smooth',
            fontColor: '#166534',
            fontSize: 12,
            fontWeight: 500,
            horzAlign: 'center',
            vertAlign: 'middle',
            customData: { fontSize: 12 },
          },
          {
            type: 'Rectangle',
            left: 20,
            top: 165,
            width: 230,
            height: 85,
            corners: [4, 4, 4, 4],
            fillColor: '#dcfce7',
            strokeColor: '#86efac',
            strokeWidth: 1,
            text: '⚡ Fast PR review\ncycles',
            fontColor: '#166534',
            fontSize: 12,
            fontWeight: 500,
            horzAlign: 'center',
            vertAlign: 'middle',
            customData: { fontSize: 12 },
          },
          {
            type: 'Frame',
            name: '🔴 To Improve',
            title: '🔴 To Improve',
            left: 300,
            top: 0,
            width: 270,
            height: 580,
            corners: [8, 8, 8, 8],
            fillColor: '#fef2f2',
            strokeColor: '#ef4444',
            strokeWidth: 2,
          },
          {
            type: 'Rectangle',
            left: 320,
            top: 55,
            width: 230,
            height: 85,
            corners: [4, 4, 4, 4],
            fillColor: '#fee2e2',
            strokeColor: '#fca5a5',
            strokeWidth: 1,
            text: '⏱️ Flaky CI pipeline\nslows deploys',
            fontColor: '#991b1b',
            fontSize: 12,
            fontWeight: 500,
            horzAlign: 'center',
            vertAlign: 'middle',
            customData: { fontSize: 12 },
          },
          {
            type: 'Rectangle',
            left: 320,
            top: 165,
            width: 230,
            height: 85,
            corners: [4, 4, 4, 4],
            fillColor: '#fee2e2',
            strokeColor: '#fca5a5',
            strokeWidth: 1,
            text: '🔄 Mid-sprint\nrequirement shifts',
            fontColor: '#991b1b',
            fontSize: 12,
            fontWeight: 500,
            horzAlign: 'center',
            vertAlign: 'middle',
            customData: { fontSize: 12 },
          },
          {
            type: 'Frame',
            name: '🔵 Action Items',
            title: '🔵 Action Items',
            left: 600,
            top: 0,
            width: 270,
            height: 580,
            corners: [8, 8, 8, 8],
            fillColor: '#eff6ff',
            strokeColor: '#3b82f6',
            strokeWidth: 2,
          },
          {
            type: 'Rectangle',
            left: 620,
            top: 55,
            width: 230,
            height: 85,
            corners: [4, 4, 4, 4],
            fillColor: '#dbeafe',
            strokeColor: '#93c5fd',
            strokeWidth: 1,
            text: '🛠️ Fix e2e test\ntimeouts',
            fontColor: '#1e40af',
            fontSize: 12,
            fontWeight: 500,
            horzAlign: 'center',
            vertAlign: 'middle',
            customData: { fontSize: 12 },
          },
          {
            type: 'Rectangle',
            left: 620,
            top: 165,
            width: 230,
            height: 85,
            corners: [4, 4, 4, 4],
            fillColor: '#dbeafe',
            strokeColor: '#93c5fd',
            strokeWidth: 1,
            text: '📝 Update API\ncontract specs',
            fontColor: '#1e40af',
            fontSize: 12,
            fontWeight: 500,
            horzAlign: 'center',
            vertAlign: 'middle',
            customData: { fontSize: 12 },
          },
        ],
      },
      {
        id: 'agile-mad-sad-glad',
        name: 'Mad / Sad / Glad Retro',
        category: StencilCategory.AGILE_SPRINT,
        description: 'Emotional retrospective board with Mad, Sad, and Glad sections',
        width: 870,
        height: 580,
        shapes: [
          {
            type: 'Frame',
            name: '😡 MAD',
            title: '😡 MAD',
            left: 0,
            top: 0,
            width: 270,
            height: 580,
            corners: [8, 8, 8, 8],
            fillColor: '#fff1f2',
            strokeColor: '#f43f5e',
            strokeWidth: 2,
          },
          {
            type: 'Rectangle',
            left: 20,
            top: 55,
            width: 230,
            height: 85,
            corners: [4, 4, 4, 4],
            fillColor: '#ffe4e6',
            strokeColor: '#fda4af',
            strokeWidth: 1,
            text: '🚧 Blocked on third-party\nauth service',
            fontColor: '#9f1239',
            fontSize: 12,
            fontWeight: 500,
            horzAlign: 'center',
            vertAlign: 'middle',
            customData: { fontSize: 12 },
          },
          {
            type: 'Rectangle',
            left: 20,
            top: 165,
            width: 230,
            height: 85,
            corners: [4, 4, 4, 4],
            fillColor: '#ffe4e6',
            strokeColor: '#fda4af',
            strokeWidth: 1,
            text: '📢 Unclear escalation\npaths',
            fontColor: '#9f1239',
            fontSize: 12,
            fontWeight: 500,
            horzAlign: 'center',
            vertAlign: 'middle',
            customData: { fontSize: 12 },
          },
          {
            type: 'Frame',
            name: '😢 SAD',
            title: '😢 SAD',
            left: 300,
            top: 0,
            width: 270,
            height: 580,
            corners: [8, 8, 8, 8],
            fillColor: '#f8fafc',
            strokeColor: '#64748b',
            strokeWidth: 2,
          },
          {
            type: 'Rectangle',
            left: 320,
            top: 55,
            width: 230,
            height: 85,
            corners: [4, 4, 4, 4],
            fillColor: '#e2e8f0',
            strokeColor: '#cbd5e1',
            strokeWidth: 1,
            text: '📉 Missed target sprint\nrelease date',
            fontColor: '#334155',
            fontSize: 12,
            fontWeight: 500,
            horzAlign: 'center',
            vertAlign: 'middle',
            customData: { fontSize: 12 },
          },
          {
            type: 'Rectangle',
            left: 320,
            top: 165,
            width: 230,
            height: 85,
            corners: [4, 4, 4, 4],
            fillColor: '#e2e8f0',
            strokeColor: '#cbd5e1',
            strokeWidth: 1,
            text: '💬 Low customer\nfeedback turnaround',
            fontColor: '#334155',
            fontSize: 12,
            fontWeight: 500,
            horzAlign: 'center',
            vertAlign: 'middle',
            customData: { fontSize: 12 },
          },
          {
            type: 'Frame',
            name: '😄 GLAD',
            title: '😄 GLAD',
            left: 600,
            top: 0,
            width: 270,
            height: 580,
            corners: [8, 8, 8, 8],
            fillColor: '#fefce8',
            strokeColor: '#eab308',
            strokeWidth: 2,
          },
          {
            type: 'Rectangle',
            left: 620,
            top: 55,
            width: 230,
            height: 85,
            corners: [4, 4, 4, 4],
            fillColor: '#fef9c3',
            strokeColor: '#fde047',
            strokeWidth: 1,
            text: '🏆 Shipped multi-board\nexport feature',
            fontColor: '#854d0e',
            fontSize: 12,
            fontWeight: 500,
            horzAlign: 'center',
            vertAlign: 'middle',
            customData: { fontSize: 12 },
          },
          {
            type: 'Rectangle',
            left: 620,
            top: 165,
            width: 230,
            height: 85,
            corners: [4, 4, 4, 4],
            fillColor: '#fef9c3',
            strokeColor: '#fde047',
            strokeWidth: 1,
            text: '🙌 Awesome pair\nprogramming vibes',
            fontColor: '#854d0e',
            fontSize: 12,
            fontWeight: 500,
            horzAlign: 'center',
            vertAlign: 'middle',
            customData: { fontSize: 12 },
          },
        ],
      },
      {
        id: 'agile-sailboat-retro',
        name: 'Sailboat Retrospective',
        category: StencilCategory.AGILE_SPRINT,
        description: 'Sailboat framework with Wind/Propellers, Anchors, and Rocks/Risks',
        width: 800,
        height: 600,
        shapes: [
          {
            type: 'Frame',
            name: '💨 Wind / Propellers',
            title: '💨 Wind / Propellers',
            left: 0,
            top: 0,
            width: 380,
            height: 280,
            corners: [8, 8, 8, 8],
            fillColor: '#ecfdf5',
            strokeColor: '#10b981',
            strokeWidth: 2,
          },
          {
            type: 'Rectangle',
            left: 20,
            top: 55,
            width: 340,
            height: 70,
            corners: [4, 4, 4, 4],
            fillColor: '#d1fae5',
            strokeColor: '#6ee7b7',
            strokeWidth: 1,
            text: '⚡ Efficient automated\nCI testing',
            fontColor: '#065f46',
            fontSize: 12,
            fontWeight: 500,
            horzAlign: 'center',
            vertAlign: 'middle',
            customData: { fontSize: 12 },
          },
          {
            type: 'Rectangle',
            left: 20,
            top: 150,
            width: 340,
            height: 70,
            corners: [4, 4, 4, 4],
            fillColor: '#d1fae5',
            strokeColor: '#6ee7b7',
            strokeWidth: 1,
            text: '🤝 Clear team\ncommunication',
            fontColor: '#065f46',
            fontSize: 12,
            fontWeight: 500,
            horzAlign: 'center',
            vertAlign: 'middle',
            customData: { fontSize: 12 },
          },
          {
            type: 'Frame',
            name: '🏝️ Destination / Goals',
            title: '🏝️ Destination / Goals',
            left: 420,
            top: 0,
            width: 380,
            height: 280,
            corners: [8, 8, 8, 8],
            fillColor: '#fff7ed',
            strokeColor: '#f97316',
            strokeWidth: 2,
          },
          {
            type: 'Rectangle',
            left: 440,
            top: 55,
            width: 340,
            height: 70,
            corners: [4, 4, 4, 4],
            fillColor: '#ffedd5',
            strokeColor: '#fdba74',
            strokeWidth: 1,
            text: '🎯 Deliver Q3 milestone\non schedule',
            fontColor: '#9a3412',
            fontSize: 12,
            fontWeight: 500,
            horzAlign: 'center',
            vertAlign: 'middle',
            customData: { fontSize: 12 },
          },
          {
            type: 'Rectangle',
            left: 440,
            top: 150,
            width: 340,
            height: 70,
            corners: [4, 4, 4, 4],
            fillColor: '#ffedd5',
            strokeColor: '#fdba74',
            strokeWidth: 1,
            text: '📈 Reach 99.9%\nuptime SLO',
            fontColor: '#9a3412',
            fontSize: 12,
            fontWeight: 500,
            horzAlign: 'center',
            vertAlign: 'middle',
            customData: { fontSize: 12 },
          },
          {
            type: 'Frame',
            name: '⚓ Anchors',
            title: '⚓ Anchors',
            left: 0,
            top: 320,
            width: 380,
            height: 280,
            corners: [8, 8, 8, 8],
            fillColor: '#f8fafc',
            strokeColor: '#64748b',
            strokeWidth: 2,
          },
          {
            type: 'Rectangle',
            left: 20,
            top: 375,
            width: 340,
            height: 70,
            corners: [4, 4, 4, 4],
            fillColor: '#e2e8f0',
            strokeColor: '#cbd5e1',
            strokeWidth: 1,
            text: '⏳ Slow PR review\nturnaround',
            fontColor: '#1e293b',
            fontSize: 12,
            fontWeight: 500,
            horzAlign: 'center',
            vertAlign: 'middle',
            customData: { fontSize: 12 },
          },
          {
            type: 'Rectangle',
            left: 20,
            top: 470,
            width: 340,
            height: 70,
            corners: [4, 4, 4, 4],
            fillColor: '#e2e8f0',
            strokeColor: '#cbd5e1',
            strokeWidth: 1,
            text: '📦 Legacy dependency\nconstraints',
            fontColor: '#1e293b',
            fontSize: 12,
            fontWeight: 500,
            horzAlign: 'center',
            vertAlign: 'middle',
            customData: { fontSize: 12 },
          },
          {
            type: 'Frame',
            name: '🪨 Rocks / Risks',
            title: '🪨 Rocks / Risks',
            left: 420,
            top: 320,
            width: 380,
            height: 280,
            corners: [8, 8, 8, 8],
            fillColor: '#fef2f2',
            strokeColor: '#ef4444',
            strokeWidth: 2,
          },
          {
            type: 'Rectangle',
            left: 440,
            top: 375,
            width: 340,
            height: 70,
            corners: [4, 4, 4, 4],
            fillColor: '#fee2e2',
            strokeColor: '#fca5a5',
            strokeWidth: 1,
            text: '⚠️ External API rate limits\napproaching',
            fontColor: '#991b1b',
            fontSize: 12,
            fontWeight: 500,
            horzAlign: 'center',
            vertAlign: 'middle',
            customData: { fontSize: 12 },
          },
          {
            type: 'Rectangle',
            left: 440,
            top: 470,
            width: 340,
            height: 70,
            corners: [4, 4, 4, 4],
            fillColor: '#fee2e2',
            strokeColor: '#fca5a5',
            strokeWidth: 1,
            text: '🔒 Upcoming security\ncompliance audit',
            fontColor: '#991b1b',
            fontSize: 12,
            fontWeight: 500,
            horzAlign: 'center',
            vertAlign: 'middle',
            customData: { fontSize: 12 },
          },
        ],
      },
      {
        id: 'agile-kanban-board',
        name: 'Kanban Stages Board',
        category: StencilCategory.AGILE_SPRINT,
        description: '4 Kanban columns with WIP limit headers (Backlog, In Progress, Review, Done)',
        width: 1210,
        height: 600,
        shapes: [
          {
            type: 'Frame',
            name: '📋 Backlog (∞)',
            title: '📋 Backlog (∞)',
            left: 0,
            top: 0,
            width: 280,
            height: 600,
            corners: [8, 8, 8, 8],
            fillColor: '#f8fafc',
            strokeColor: '#94a3b8',
            strokeWidth: 1.5,
          },
          {
            type: 'Custom',
            left: 20,
            top: 55,
            width: 240,
            height: 160,
            script: DRAW_SCRIPTS.agileStoryCard,
            properties: {
              code: 'US-101',
              title: 'User OAuth2 Sign In',
              persona: 'As a User',
              goal: 'I want Google & GitHub SSO',
              value: 'So that I log in securely',
              points: '5',
              status: 'BACKLOG',
            },
            fillColor: '#fefce8',
            strokeColor: '#eab308',
            strokeWidth: 2,
            fontColor: '#713f12',
          },
          {
            type: 'Custom',
            left: 20,
            top: 235,
            width: 240,
            height: 160,
            script: DRAW_SCRIPTS.agileStoryCard,
            properties: {
              code: 'US-102',
              title: 'Email Notifications',
              persona: 'As an Admin',
              goal: 'I want instant email alerts',
              value: 'So that I stay informed',
              points: '3',
              status: 'BACKLOG',
            },
            fillColor: '#fefce8',
            strokeColor: '#eab308',
            strokeWidth: 2,
            fontColor: '#713f12',
          },
          {
            type: 'Frame',
            name: '⚡ In Progress [WIP: 3]',
            title: '⚡ In Progress [WIP: 3]',
            left: 310,
            top: 0,
            width: 280,
            height: 600,
            corners: [8, 8, 8, 8],
            fillColor: '#eff6ff',
            strokeColor: '#60a5fa',
            strokeWidth: 1.5,
          },
          {
            type: 'Custom',
            left: 330,
            top: 55,
            width: 240,
            height: 160,
            script: DRAW_SCRIPTS.agileStoryCard,
            properties: {
              code: 'US-103',
              title: 'Real-time Analytics',
              persona: 'As an Analyst',
              goal: 'I want live metrics charts',
              value: 'So that I monitor traffic',
              points: '8',
              status: 'IN PROGRESS',
            },
            fillColor: '#fefce8',
            strokeColor: '#eab308',
            strokeWidth: 2,
            fontColor: '#713f12',
          },
          {
            type: 'Frame',
            name: '🔍 In Review [WIP: 2]',
            title: '🔍 In Review [WIP: 2]',
            left: 620,
            top: 0,
            width: 280,
            height: 600,
            corners: [8, 8, 8, 8],
            fillColor: '#fdf4ff',
            strokeColor: '#c084fc',
            strokeWidth: 1.5,
          },
          {
            type: 'Custom',
            left: 640,
            top: 55,
            width: 240,
            height: 160,
            script: DRAW_SCRIPTS.agileStoryCard,
            properties: {
              code: 'US-104',
              title: 'Dark Mode UI Toggle',
              persona: 'As a Designer',
              goal: 'I want night mode theme',
              value: 'So that eyes do not tire',
              points: '2',
              status: 'IN REVIEW',
            },
            fillColor: '#fefce8',
            strokeColor: '#eab308',
            strokeWidth: 2,
            fontColor: '#713f12',
          },
          {
            type: 'Frame',
            name: '✅ Done',
            title: '✅ Done',
            left: 930,
            top: 0,
            width: 280,
            height: 600,
            corners: [8, 8, 8, 8],
            fillColor: '#f0fdf4',
            strokeColor: '#4ade80',
            strokeWidth: 1.5,
          },
          {
            type: 'Custom',
            left: 950,
            top: 55,
            width: 240,
            height: 160,
            script: DRAW_SCRIPTS.agileStoryCard,
            properties: {
              code: 'US-105',
              title: 'SVG Stencil Export',
              persona: 'As a Team Lead',
              goal: 'I want vector diagram export',
              value: 'So that I share designs',
              points: '3',
              status: 'DONE',
            },
            fillColor: '#fefce8',
            strokeColor: '#eab308',
            strokeWidth: 2,
            fontColor: '#713f12',
          },
        ],
      },
      {
        id: 'agile-sprint-goal',
        name: 'Sprint Goal Banner',
        category: StencilCategory.AGILE_SPRINT,
        description: 'Prominent header banner for current sprint focus and commitments',
        width: 500,
        height: 100,
        shapes: [
          {
            type: 'Rectangle',
            left: 0,
            top: 0,
            width: 500,
            height: 100,
            corners: [8, 8, 8, 8],
            fillColor: '#e0e7ff',
            strokeColor: '#4f46e5',
            strokeWidth: 2,
            text: '🎯 Sprint 24 Goal\nDeliver self-service organization billing & license allocation',
            fontColor: '#312e81',
            fontSize: 16,
            fontWeight: 700,
            horzAlign: 'center',
            vertAlign: 'middle',
          },
        ],
      },
      {
        id: 'agile-blocker-flag',
        name: 'Blocker / Flag Card',
        category: StencilCategory.AGILE_SPRINT,
        description: 'Attention-grabbing blocker callout with owner and escalation path',
        width: 240,
        height: 110,
        shapes: [
          {
            type: 'Rectangle',
            left: 0,
            top: 0,
            width: 240,
            height: 110,
            corners: [6, 6, 6, 6],
            fillColor: '#fef2f2',
            strokeColor: '#ef4444',
            strokeWidth: 2,
            text: '🚨 IMPEDIMENT / BLOCKER\n\nStuck on: OAuth2 provider rate limits\nOwner: @alex',
            fontColor: '#991b1b',
            fontSize: 13,
            fontWeight: 600,
            horzAlign: 'left',
            vertAlign: 'top',
          },
        ],
      },
      {
        id: 'agile-team-mood-meter',
        name: 'Team Mood & Confidence Meter',
        category: StencilCategory.AGILE_SPRINT,
        description: 'Scripted confidence and sprint health meter from 1 to 5',
        width: 320,
        height: 80,
        shapes: [
          {
            type: 'Custom',
            left: 0,
            top: 0,
            width: 320,
            height: 80,
            script: DRAW_SCRIPTS.agileMoodMeter,
            properties: { level: 4 },
            fillColor: '#f8fafc',
            strokeColor: '#cbd5e1',
            strokeWidth: 1.5,
          },
        ],
      },
    ],
  };
