import { StencilCategory, StencilCollection } from '@/types/shapeLibrary';
import { DRAW_SCRIPTS } from '../scripts';

export const cloudCollection: StencilCollection = {
  id: 'prebuilt-cloud-architecture',
  name: 'Cloud Architecture',
  description: 'Cloud infrastructure components for AWS, Azure, GCP, and Kubernetes',
  categories: [StencilCategory.CLOUD_ARCHITECTURE],
  isPrebuilt: true,
  stencils: [
    {
      id: 'cloud-aws-stack',
      name: 'AWS Microservice Architecture',
      category: StencilCategory.CLOUD_ARCHITECTURE,
      description: 'AWS API Gateway, Lambda serverless function, DynamoDB database, and S3 storage',
      width: 520,
      height: 220,
      shapes: [
        {
          type: 'Custom',
          left: 0,
          top: 0,
          width: 520,
          height: 220,
          script: DRAW_SCRIPTS.cloudBoundary,
          properties: { label: 'AWS Cloud VPC Container' },
          fillColor: 'rgba(255, 153, 0, 0.06)',
          strokeColor: '#ff9900',
          strokeWidth: 1.5,
        },
        { type: 'Rectangle', left: 20, top: 55, width: 130, height: 70, corners: [6, 6, 6, 6], fillColor: '#ffffff', strokeColor: '#ff9900', strokeWidth: 2, text: 'API Gateway\n(REST HTTP)', fontColor: '#1e293b', fontSize: 13, fontWeight: 500, horzAlign: 'center', vertAlign: 'middle' },
        { type: 'Rectangle', left: 180, top: 55, width: 140, height: 70, corners: [6, 6, 6, 6], fillColor: '#ffffff', strokeColor: '#ff9900', strokeWidth: 2, text: 'AWS Lambda\n(Execution Engine)', fontColor: '#1e293b', fontSize: 13, fontWeight: 500, horzAlign: 'center', vertAlign: 'middle' },
        {
          type: 'Custom',
          left: 350,
          top: 45,
          width: 150,
          height: 75,
          script: DRAW_SCRIPTS.databaseCylinder,
          properties: { title: 'DynamoDB', subtitle: 'NoSQL Table' },
          fillColor: '#eff6ff',
          strokeColor: '#2563eb',
          strokeWidth: 2,
        },
        { type: 'Rectangle', left: 350, top: 135, width: 150, height: 60, corners: [6, 6, 6, 6], fillColor: '#ffffff', strokeColor: '#10b981', strokeWidth: 2, text: 'Amazon S3\n(Blob Assets)', fontColor: '#1e293b', fontSize: 13, fontWeight: 500, horzAlign: 'center', vertAlign: 'middle' },
      ],
    },
    {
      id: 'cloud-k8s-cluster',
      name: 'Kubernetes Pod & Service',
      category: StencilCategory.CLOUD_ARCHITECTURE,
      description: 'Kubernetes Cluster with Ingress, Service routing, and Worker Pod replicas',
      width: 480,
      height: 240,
      shapes: [
        {
          type: 'Custom',
          left: 0,
          top: 0,
          width: 480,
          height: 240,
          script: DRAW_SCRIPTS.cloudBoundary,
          properties: { label: 'Kubernetes Cluster (k8s)' },
          fillColor: 'rgba(50, 108, 229, 0.06)',
          strokeColor: '#326ce5',
          strokeWidth: 1.5,
        },
        { type: 'Rectangle', left: 20, top: 60, width: 120, height: 80, corners: [6, 6, 6, 6], fillColor: '#ffffff', strokeColor: '#326ce5', strokeWidth: 2, text: 'Ingress\nController', fontColor: '#0f172a', fontSize: 13, fontWeight: 500, horzAlign: 'center', vertAlign: 'middle' },
        { type: 'Rectangle', left: 170, top: 60, width: 120, height: 80, corners: [6, 6, 6, 6], fillColor: '#ffffff', strokeColor: '#326ce5', strokeWidth: 2, text: 'ClusterIP\nService', fontColor: '#0f172a', fontSize: 13, fontWeight: 500, horzAlign: 'center', vertAlign: 'middle' },
        { type: 'Rectangle', left: 320, top: 40, width: 130, height: 60, corners: [6, 6, 6, 6], fillColor: '#eff6ff', strokeColor: '#60a5fa', strokeWidth: 1.5, text: 'Pod: app-replica-1', fontColor: '#1e3a8a', fontSize: 12, fontWeight: 500, horzAlign: 'center', vertAlign: 'middle' },
        { type: 'Rectangle', left: 320, top: 120, width: 130, height: 60, corners: [6, 6, 6, 6], fillColor: '#eff6ff', strokeColor: '#60a5fa', strokeWidth: 1.5, text: 'Pod: app-replica-2', fontColor: '#1e3a8a', fontSize: 12, fontWeight: 500, horzAlign: 'center', vertAlign: 'middle' },
      ],
    },
    {
      id: 'cloud-server-node',
      name: 'Database & Compute Node',
      category: StencilCategory.CLOUD_ARCHITECTURE,
      description: 'Scripted 3D Database cylinder and compute server blade rack',
      width: 360,
      height: 160,
      shapes: [
        {
          type: 'Custom',
          left: 0,
          top: 10,
          width: 160,
          height: 140,
          script: DRAW_SCRIPTS.databaseCylinder,
          properties: { title: 'Primary DB', subtitle: 'PostgreSQL 16' },
          fillColor: '#eff6ff',
          strokeColor: '#2563eb',
          strokeWidth: 2,
        },
        {
          type: 'Custom',
          left: 180,
          top: 10,
          width: 180,
          height: 140,
          script: DRAW_SCRIPTS.serverBladeRack,
          properties: { label: 'Worker Rack Node-01', status: 'ONLINE' },
          fillColor: '#1e293b',
          strokeColor: '#475569',
          strokeWidth: 2,
        },
      ],
    },
    {
      id: 'cloud-azure-service-block',
      name: 'Azure Cloud Service Group',
      category: StencilCategory.CLOUD_ARCHITECTURE,
      description: 'Azure App Service, Azure SQL Database, and Azure Blob Storage',
      width: 360,
      height: 200,
      shapes: [
        {
          type: 'Custom',
          left: 0,
          top: 0,
          width: 360,
          height: 200,
          script: DRAW_SCRIPTS.cloudBoundary,
          properties: { label: 'Azure Resource Group' },
          fillColor: 'rgba(0, 120, 212, 0.06)',
          strokeColor: '#0078d4',
          strokeWidth: 1.5,
        },
        { type: 'Rectangle', left: 20, top: 45, width: 140, height: 60, corners: [6, 6, 6, 6], fillColor: '#ffffff', strokeColor: '#0078d4', strokeWidth: 2, text: 'Azure App Service', fontColor: '#0f172a', fontSize: 13, fontWeight: 500, horzAlign: 'center', vertAlign: 'middle' },
        {
          type: 'Custom',
          left: 190,
          top: 40,
          width: 145,
          height: 70,
          script: DRAW_SCRIPTS.databaseCylinder,
          properties: { title: 'Azure SQL DB', subtitle: 'Relational' },
          fillColor: '#eff6ff',
          strokeColor: '#0078d4',
          strokeWidth: 2,
        },
        { type: 'Rectangle', left: 105, top: 125, width: 150, height: 55, corners: [6, 6, 6, 6], fillColor: '#ffffff', strokeColor: '#0078d4', strokeWidth: 2, text: 'Blob Storage Container', fontColor: '#0f172a', fontSize: 13, fontWeight: 500, horzAlign: 'center', vertAlign: 'middle' },
      ],
    },
  ],
};
