import { StencilCategory, StencilCollection } from '@/types/shapeLibrary';
import { DRAW_SCRIPTS } from '../scripts';

export const umlCollection: StencilCollection = {
  id: 'prebuilt-software-uml',
  name: 'Software Design & UML',
  description: 'UML class diagrams, sequence flows, ER database schemas, and state machines',
  categories: [StencilCategory.SOFTWARE_DESIGN_UML],
  isPrebuilt: true,
  stencils: [
    {
      id: 'uml-class-box',
      name: 'UML Class Box',
      category: StencilCategory.SOFTWARE_DESIGN_UML,
      description: 'Scripted 3-compartment UML class box with distinct header, attributes, and operations',
      width: 220,
      height: 170,
      shapes: [
        {
          type: 'Custom',
          left: 0,
          top: 0,
          width: 220,
          height: 170,
          script: DRAW_SCRIPTS.umlClassBox,
          properties: {
            className: 'UserAccount',
            stereotype: '<<Entity>>',
            attributes: ['- id: UUID', '- email: String', '- role: UserRole'],
            methods: ['+ hasPermission(): Boolean', '+ updateProfile(): void'],
          },
          fillColor: '#ffffff',
          strokeColor: '#334155',
          strokeWidth: 2,
        },
      ],
    },
    {
      id: 'uml-er-table',
      name: 'ER Database Table',
      category: StencilCategory.SOFTWARE_DESIGN_UML,
      description: 'Relational database table entity with Primary Key and Foreign Key indicators',
      width: 240,
      height: 160,
      shapes: [
        {
          type: 'Rectangle',
          left: 0,
          top: 0,
          width: 240,
          height: 160,
          corners: [4, 4, 4, 4],
          fillColor: '#eff6ff',
          strokeColor: '#2563eb',
          strokeWidth: 2,
          text: 'TABLE: whiteboard_snapshot\n=========================\n[PK] id: UUID\n[FK] whiteboard_id: UUID\n[NN] version: INT\n[NN] created_by: UUID\n     name: VARCHAR(255)\n     content: JSONB',
          fontColor: '#1e3a8a',
          fontSize: 12,
          fontWeight: 500,
          horzAlign: 'left',
          vertAlign: 'top',
        },
      ],
    },
    {
      id: 'uml-state-node',
      name: 'State Machine Node',
      category: StencilCategory.SOFTWARE_DESIGN_UML,
      description: 'State machine node with entry, do, and exit action definitions',
      width: 180,
      height: 100,
      shapes: [
        {
          type: 'Rectangle',
          left: 0,
          top: 0,
          width: 180,
          height: 100,
          corners: [16, 16, 16, 16],
          fillColor: '#f1f5f9',
          strokeColor: '#475569',
          strokeWidth: 2,
          text: 'ActiveState\n---\nentry / initSession()\ndo / pollEvents()\nexit / flushState()',
          fontColor: '#0f172a',
          fontSize: 12,
          fontWeight: 500,
          horzAlign: 'center',
          vertAlign: 'top',
        },
      ],
    },
  ],
};
