// @vitest-environment jsdom
import { describe, it, expect, vi, afterEach } from 'vitest';
import { render, screen, cleanup, waitFor, fireEvent } from '@testing-library/react';
import React from 'react';
import { HistoryDrawer } from './HistoryDrawer';
import * as api from '@/lib/api';
import * as entitlementContext from '@/lib/entitlementContext';

describe('HistoryDrawer', () => {
  afterEach(() => {
    cleanup();
    vi.restoreAllMocks();
  });

  const mockEntitledContext = (entitled = true) => {
    vi.spyOn(entitlementContext, 'useEntitlements').mockReturnValue({
      plan: entitled ? 'PRO' : 'FREE',
      status: 'ACTIVE',
      isExpired: false,
      validUntil: null,
      entitlements: null,
      loading: false,
      hasFeature: (feature: string) => (entitled ? feature === 'whiteboard:version_history' : false),
      getQuota: () => ({ current: 0, limit: 10, remaining: 10, isUnlimited: false, allowed: true }),
      refreshEntitlements: async () => {},
      activateKey: async () => {},
      deactivateKey: async () => {},
    });
  };

  it('renders upgrade prompt when feature is not entitled on FREE plan', async () => {
    mockEntitledContext(false);

    render(
      <HistoryDrawer
        isOpen={true}
        onClose={vi.fn()}
        boardId="test-board-1"
        boardName="Architecture Board"
        currentUserRole="OWNER"
        currentUserId="user-1"
      />
    );

    expect(screen.getByText('Unlock Version History')).toBeDefined();
    expect(screen.getByText(/Upgrade Plan/i)).toBeDefined();
  });

  it('renders snapshot timeline when entitled on PRO plan', async () => {
    mockEntitledContext(true);

    vi.spyOn(api, 'listSnapshots').mockResolvedValue([
      {
        id: 'snap-2',
        whiteboardId: 'test-board-1',
        name: 'Sprint 1 Architecture',
        description: 'Approved baseline design',
        isAutomatic: false,
        createdBy: 'user-1',
        createdAt: '2026-09-09T09:00:00Z',
      },
      {
        id: 'snap-1',
        whiteboardId: 'test-board-1',
        name: 'Initial state',
        description: null,
        isAutomatic: true,
        createdBy: 'user-1',
        createdAt: '2026-09-09T08:00:00Z',
      },
    ]);

    render(
      <HistoryDrawer
        isOpen={true}
        onClose={vi.fn()}
        boardId="test-board-1"
        boardName="Architecture Board"
        currentUserRole="OWNER"
        currentUserId="user-1"
      />
    );

    await waitFor(() => {
      expect(screen.getByText('Revision History (2)')).toBeDefined();
      expect(screen.getByText('Sprint 1 Architecture')).toBeDefined();
      expect(screen.getByText('Approved baseline design')).toBeDefined();
      expect(screen.getByText('Initial state')).toBeDefined();
      expect(screen.getByText('Milestone')).toBeDefined();
      expect(screen.getByText('Auto')).toBeDefined();
      expect(screen.queryByText('v2')).toBeNull();
      expect(screen.queryByText('v1')).toBeNull();
    });
  });

  it('renders AI badge for snapshots generated by AI', async () => {
    mockEntitledContext(true);

    vi.spyOn(api, 'listSnapshots').mockResolvedValue([
      {
        id: 'snap-ai-1',
        whiteboardId: 'test-board-1',
        name: 'AI Generated Architecture',
        description: 'Generated from user prompt',
        isAutomatic: false,
        isGeneratedByAI: true,
        createdBy: 'user-1',
        createdAt: '2026-09-09T10:00:00Z',
      },
    ]);

    render(
      <HistoryDrawer
        isOpen={true}
        onClose={vi.fn()}
        boardId="test-board-1"
        boardName="Architecture Board"
        currentUserRole="OWNER"
        currentUserId="user-1"
      />
    );

    await waitFor(() => {
      expect(screen.getByText('AI Generated Architecture')).toBeDefined();
      expect(screen.getByText('AI')).toBeDefined();
    });
  });

  it('allows creating a manual checkpoint snapshot', async () => {
    mockEntitledContext(true);

    vi.spyOn(api, 'listSnapshots').mockResolvedValue([]);
    const createSpy = vi.spyOn(api, 'createSnapshot').mockResolvedValue({
      id: 'snap-created',
      whiteboardId: 'test-board-1',
      name: 'Release 1.0 Milestone',
      description: 'Production schema ready',
      isAutomatic: false,
      createdBy: 'user-1',
      createdAt: '2026-09-09T09:30:00Z',
    });

    render(
      <HistoryDrawer
        isOpen={true}
        onClose={vi.fn()}
        boardId="test-board-1"
        boardName="Architecture Board"
        currentUserRole="OWNER"
        currentUserId="user-1"
      />
    );

    await waitFor(() => {
      expect(screen.getByText(/Create Named Checkpoint/i)).toBeDefined();
    });

    fireEvent.click(screen.getByText(/Create Named Checkpoint/i));

    const nameInput = screen.getByPlaceholderText(/Milestone name/i);
    const descInput = screen.getByPlaceholderText(/Optional milestone notes/i);

    fireEvent.change(nameInput, { target: { value: 'Release 1.0 Milestone' } });
    fireEvent.change(descInput, { target: { value: 'Production schema ready' } });

    fireEvent.click(screen.getByText('Save Checkpoint'));

    await waitFor(() => {
      expect(createSpy).toHaveBeenCalledWith('test-board-1', {
        name: 'Release 1.0 Milestone',
        description: 'Production schema ready',
      });
    });
  });

  it('triggers snapshot restore after confirmation modal', async () => {
    mockEntitledContext(true);

    const snapshotSummary: api.WhiteboardSnapshotSummary = {
      id: 'snap-1',
      whiteboardId: 'test-board-1',
      name: 'State Alpha',
      description: 'First version',
      isAutomatic: false,
      createdBy: 'user-1',
      createdAt: '2026-09-09T08:00:00Z',
    };

    const fullSnapshot: api.WhiteboardSnapshot = {
      ...snapshotSummary,
      content: { id: 'doc-1', version: 1, children: [] },
    };

    vi.spyOn(api, 'listSnapshots').mockResolvedValue([snapshotSummary]);
    vi.spyOn(api, 'getSnapshot').mockResolvedValue(fullSnapshot);
    const restoreSpy = vi.spyOn(api, 'restoreSnapshot').mockResolvedValue({
      id: 'test-board-1',
      name: 'Architecture Board',
      content: fullSnapshot.content,
    });

    const onRestoreMock = vi.fn();

    render(
      <HistoryDrawer
        isOpen={true}
        onClose={vi.fn()}
        boardId="test-board-1"
        boardName="Architecture Board"
        currentUserRole="OWNER"
        currentUserId="user-1"
        onRestoreSnapshot={onRestoreMock}
      />
    );

    await waitFor(() => {
      expect(screen.getByText('Restore')).toBeDefined();
    });

    fireEvent.click(screen.getByText('Restore'));

    await waitFor(() => {
      expect(screen.getByText(/Restore to snapshot\?/i)).toBeDefined();
    });

    fireEvent.click(screen.getByText('Confirm Restore'));

    await waitFor(() => {
      expect(restoreSpy).toHaveBeenCalledWith('test-board-1', 'snap-1');
      expect(onRestoreMock).toHaveBeenCalledWith(fullSnapshot);
    });
  });

  it('triggers fork modal and creates forked whiteboard', async () => {
    mockEntitledContext(true);

    const snapshotSummary: api.WhiteboardSnapshotSummary = {
      id: 'snap-1',
      whiteboardId: 'test-board-1',
      name: 'State Alpha',
      description: null,
      isAutomatic: false,
      createdBy: 'user-1',
      createdAt: '2026-09-09T08:00:00Z',
    };

    vi.spyOn(api, 'listSnapshots').mockResolvedValue([snapshotSummary]);
    const forkSpy = vi.spyOn(api, 'forkSnapshot').mockResolvedValue({
      id: 'forked-board-id',
      name: 'Architecture Board (Fork)',
      content: null,
    });

    const onForkMock = vi.fn();

    render(
      <HistoryDrawer
        isOpen={true}
        onClose={vi.fn()}
        boardId="test-board-1"
        boardName="Architecture Board"
        currentUserRole="OWNER"
        currentUserId="user-1"
        onForkSuccess={onForkMock}
      />
    );

    await waitFor(() => {
      expect(screen.getByText('Fork')).toBeDefined();
    });

    fireEvent.click(screen.getByText('Fork'));

    await waitFor(() => {
      expect(screen.getByText('Fork Snapshot')).toBeDefined();
    });

    fireEvent.click(screen.getByText('Create Fork'));

    await waitFor(() => {
      expect(forkSpy).toHaveBeenCalledWith('test-board-1', 'snap-1', {
        name: 'Architecture Board (Fork)',
      });
      expect(onForkMock).toHaveBeenCalledWith('forked-board-id');
    });
  });

  it('does not exit preview when drawer is closed', async () => {
    mockEntitledContext(true);
    vi.spyOn(api, 'listSnapshots').mockResolvedValue([
      {
        id: 'snap-1',
        whiteboardId: 'test-board-1',
        name: 'State Alpha',
        description: null,
        isAutomatic: false,
        createdBy: 'user-1',
        createdAt: '2026-09-09T08:00:00Z',
      },
    ]);

    const onPreviewMock = vi.fn();

    const { rerender } = render(
      <HistoryDrawer
        isOpen={true}
        onClose={vi.fn()}
        boardId="test-board-1"
        boardName="Architecture Board"
        currentUserRole="OWNER"
        currentUserId="user-1"
        onPreviewSnapshot={onPreviewMock}
        previewSnapshotId="snap-1"
      />
    );

    await waitFor(() => {
      expect(screen.getByText('State Alpha')).toBeDefined();
    });

    // Rerender with isOpen=false (closing drawer)
    rerender(
      <HistoryDrawer
        isOpen={false}
        onClose={vi.fn()}
        boardId="test-board-1"
        boardName="Architecture Board"
        currentUserRole="OWNER"
        currentUserId="user-1"
        onPreviewSnapshot={onPreviewMock}
        previewSnapshotId="snap-1"
      />
    );

    // Verify onPreviewSnapshot was NOT called with null on drawer close
    expect(onPreviewMock).not.toHaveBeenCalledWith(null);
  });

  it('fetches snapshot list freshly whenever drawer opens', async () => {
    mockEntitledContext(true);
    const listSpy = vi.spyOn(api, 'listSnapshots').mockResolvedValue([]);

    const { rerender } = render(
      <HistoryDrawer
        isOpen={false}
        onClose={vi.fn()}
        boardId="test-board-1"
        boardName="Architecture Board"
        currentUserRole="OWNER"
        currentUserId="user-1"
      />
    );

    expect(listSpy).not.toHaveBeenCalled();

    rerender(
      <HistoryDrawer
        isOpen={true}
        onClose={vi.fn()}
        boardId="test-board-1"
        boardName="Architecture Board"
        currentUserRole="OWNER"
        currentUserId="user-1"
      />
    );

    await waitFor(() => {
      expect(listSpy).toHaveBeenCalledWith('test-board-1', 0, 50);
    });
  });

  it('handles 404 on preview by displaying error and refreshing snapshot list', async () => {
    mockEntitledContext(true);
    const listSpy = vi.spyOn(api, 'listSnapshots').mockResolvedValue([
      {
        id: 'snap-stale',
        whiteboardId: 'test-board-1',
        name: 'Pruned Snapshot',
        description: null,
        isAutomatic: true,
        createdBy: 'user-1',
        createdAt: '2026-09-09T08:00:00Z',
      },
    ]);

    const error404: any = new Error('Snapshot not found');
    error404.status = 404;
    vi.spyOn(api, 'getSnapshot').mockRejectedValue(error404);

    const onPreviewMock = vi.fn();

    render(
      <HistoryDrawer
        isOpen={true}
        onClose={vi.fn()}
        boardId="test-board-1"
        boardName="Architecture Board"
        currentUserRole="OWNER"
        currentUserId="user-1"
        onPreviewSnapshot={onPreviewMock}
      />
    );

    await waitFor(() => {
      expect(screen.getByText('Preview')).toBeDefined();
    });

    listSpy.mockClear();

    fireEvent.click(screen.getByText('Preview'));

    await waitFor(() => {
      expect(screen.getByText(/Snapshot is no longer available/i)).toBeDefined();
      expect(listSpy).toHaveBeenCalledWith('test-board-1', 0, 50);
      expect(onPreviewMock).not.toHaveBeenCalled();
    });
  });

  it('handles 404 on restore by displaying error and refreshing snapshot list', async () => {
    mockEntitledContext(true);
    const listSpy = vi.spyOn(api, 'listSnapshots').mockResolvedValue([
      {
        id: 'snap-stale-restore',
        whiteboardId: 'test-board-1',
        name: 'Pruned Snapshot 4',
        description: null,
        isAutomatic: true,
        createdBy: 'user-1',
        createdAt: '2026-09-09T08:00:00Z',
      },
    ]);

    const error404: any = new Error('Snapshot not found');
    error404.status = 404;
    vi.spyOn(api, 'getSnapshot').mockRejectedValue(error404);

    render(
      <HistoryDrawer
        isOpen={true}
        onClose={vi.fn()}
        boardId="test-board-1"
        boardName="Architecture Board"
        currentUserRole="OWNER"
        currentUserId="user-1"
      />
    );

    await waitFor(() => {
      expect(screen.getByText('Restore')).toBeDefined();
    });

    fireEvent.click(screen.getByText('Restore'));

    await waitFor(() => {
      expect(screen.getByRole('button', { name: /Confirm Restore/i })).toBeDefined();
    });

    listSpy.mockClear();

    fireEvent.click(screen.getByRole('button', { name: /Confirm Restore/i }));

    await waitFor(() => {
      expect(screen.getByText(/Snapshot no longer exists. Refreshing history.../i)).toBeDefined();
      expect(listSpy).toHaveBeenCalledWith('test-board-1', 0, 50);
    });
  });
});
